x-client-variables: &client-variables
  VITE_API_ENDPOINT: ${VITE_API_ENDPOINT}
  VITE_WS_ENDPOINT: ws://localhost:8000/ws/chat/


services:
  client:
    build:
      context: .
    container_name: client
    environment: *client-variables
    ports:
      - "8080:8080"
    networks:
      custom_network:
        ipv4_address: 172.20.0.5

networks:
  custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1